Some cleanup for tests 960-965 build scripts.
Make all 96* build scripts consistent and update 965 to build and run
with jack.

Change-Id: If27ee9c92880c75307a18b054ba926670877073a

diff --git a/test/965-default-verify/build b/test/965-default-verify/build
--- a/test/965-default-verify/build
+++ b/test/965-default-verify/build
@@ -17,14 +17,32 @@
 # make us exit on a failure
 set -e
 
+# Should we compile with Java source code. By default we will use Smali.
+USES_JAVA_SOURCE="false"
 if [[ $@ == *"--jvm"* ]]; then
-  # Build the Java files if we are running a --jvm test
-  mkdir -p src classes
-  ${ANDROID_BUILD_TOP}/art/tools/extract-embedded-java ./smali ./src
-  ${JAVAC} -implicit:none -d classes build-src/Statics.java src/Main.java src/Iface.java
-  rm -f classes/Statics.class
-  ${JAVAC} -implicit:none -d classes src/Statics.java
-else
-  # TODO Support building with jack.
-  ./default-build "$@" --experimental default-methods
+  USES_JAVA_SOURCE="true"
+elif [[ "$USE_JACK" == "true" ]]; then
+  if $JACK -D jack.java.source.version=1.8 2>/dev/null; then
+    USES_JAVA_SOURCE="true"
+  else
+    echo "WARNING: Cannot use jack because it does not support JLS 1.8. Falling back to smali" >&2
+  fi
 fi
+
+if [[ "$USES_JAVA_SOURCE" == "true" ]]; then
+  # We are compiling Java code, create it.
+  mkdir -p src
+  mkdir -p src2
+  ${ANDROID_BUILD_TOP}/art/tools/extract-embedded-java ./smali ./src
+  # Move build-src to src and the src copies to src2. This is needed because of
+  # how our default build script works and we wanted the java and smali code
+  # to be the same in the smali files.
+  for f in `find ./build-src -type f -name "*.java" | xargs -i basename \{\}`; do
+    mv ./src/$f ./src2/$f
+    mv ./build-src/$f ./src/$f
+  done
+  # Ignore the smali directory.
+  EXTRA_ARGS="--no-smali"
+fi
+
+./default-build "$@" "$EXTRA_ARGS" --experimental default-methods
